version: "1.0"
services: 
  database: 
    image: postgres 
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data 
    environment: 
      POSTGRES_USERNAME: postgres 
      POSTGRES_PASSWORD: password

  development:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database